// flow-typed signature: 3e2aa3d90916a8a821bf7445142d2967
// flow-typed version: <<STUB>>/deep-diff_v^1.0.2/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'deep-diff'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'deep-diff' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'deep-diff/dist/deep-diff.min' {
  declare module.exports: any;
}

declare module 'deep-diff/examples/apply-diff-from-any' {
  declare module.exports: any;
}

declare module 'deep-diff/examples/array-change' {
  declare module.exports: any;
}

declare module 'deep-diff/examples/capture_change_apply_elsewhere' {
  declare module.exports: any;
}

declare module 'deep-diff/examples/diff-ignoring-fun' {
  declare module.exports: any;
}

declare module 'deep-diff/examples/diff-scenarios' {
  declare module.exports: any;
}

declare module 'deep-diff/examples/example1' {
  declare module.exports: any;
}

declare module 'deep-diff/examples/issue-111' {
  declare module.exports: any;
}

declare module 'deep-diff/examples/issue-113-1' {
  declare module.exports: any;
}

declare module 'deep-diff/examples/issue-113-2' {
  declare module.exports: any;
}

declare module 'deep-diff/examples/issue-115' {
  declare module.exports: any;
}

declare module 'deep-diff/examples/issue-124' {
  declare module.exports: any;
}

declare module 'deep-diff/examples/issue-125' {
  declare module.exports: any;
}

declare module 'deep-diff/examples/issue-126' {
  declare module.exports: any;
}

declare module 'deep-diff/examples/issue-35' {
  declare module.exports: any;
}

declare module 'deep-diff/examples/issue-47' {
  declare module.exports: any;
}

declare module 'deep-diff/examples/issue-48' {
  declare module.exports: any;
}

declare module 'deep-diff/examples/issue-62' {
  declare module.exports: any;
}

declare module 'deep-diff/examples/issue-70' {
  declare module.exports: any;
}

declare module 'deep-diff/examples/issue-71' {
  declare module.exports: any;
}

declare module 'deep-diff/examples/issue-72' {
  declare module.exports: any;
}

declare module 'deep-diff/examples/issue-74' {
  declare module.exports: any;
}

declare module 'deep-diff/examples/issue-78' {
  declare module.exports: any;
}

declare module 'deep-diff/examples/issue-83' {
  declare module.exports: any;
}

declare module 'deep-diff/examples/issue-88' {
  declare module.exports: any;
}

declare module 'deep-diff/examples/performance' {
  declare module.exports: any;
}

declare module 'deep-diff/test/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'deep-diff/dist/deep-diff.min.js' {
  declare module.exports: $Exports<'deep-diff/dist/deep-diff.min'>;
}
declare module 'deep-diff/examples/apply-diff-from-any.js' {
  declare module.exports: $Exports<'deep-diff/examples/apply-diff-from-any'>;
}
declare module 'deep-diff/examples/array-change.js' {
  declare module.exports: $Exports<'deep-diff/examples/array-change'>;
}
declare module 'deep-diff/examples/capture_change_apply_elsewhere.js' {
  declare module.exports: $Exports<'deep-diff/examples/capture_change_apply_elsewhere'>;
}
declare module 'deep-diff/examples/diff-ignoring-fun.js' {
  declare module.exports: $Exports<'deep-diff/examples/diff-ignoring-fun'>;
}
declare module 'deep-diff/examples/diff-scenarios.js' {
  declare module.exports: $Exports<'deep-diff/examples/diff-scenarios'>;
}
declare module 'deep-diff/examples/example1.js' {
  declare module.exports: $Exports<'deep-diff/examples/example1'>;
}
declare module 'deep-diff/examples/issue-111.js' {
  declare module.exports: $Exports<'deep-diff/examples/issue-111'>;
}
declare module 'deep-diff/examples/issue-113-1.js' {
  declare module.exports: $Exports<'deep-diff/examples/issue-113-1'>;
}
declare module 'deep-diff/examples/issue-113-2.js' {
  declare module.exports: $Exports<'deep-diff/examples/issue-113-2'>;
}
declare module 'deep-diff/examples/issue-115.js' {
  declare module.exports: $Exports<'deep-diff/examples/issue-115'>;
}
declare module 'deep-diff/examples/issue-124.js' {
  declare module.exports: $Exports<'deep-diff/examples/issue-124'>;
}
declare module 'deep-diff/examples/issue-125.js' {
  declare module.exports: $Exports<'deep-diff/examples/issue-125'>;
}
declare module 'deep-diff/examples/issue-126.js' {
  declare module.exports: $Exports<'deep-diff/examples/issue-126'>;
}
declare module 'deep-diff/examples/issue-35.js' {
  declare module.exports: $Exports<'deep-diff/examples/issue-35'>;
}
declare module 'deep-diff/examples/issue-47.js' {
  declare module.exports: $Exports<'deep-diff/examples/issue-47'>;
}
declare module 'deep-diff/examples/issue-48.js' {
  declare module.exports: $Exports<'deep-diff/examples/issue-48'>;
}
declare module 'deep-diff/examples/issue-62.js' {
  declare module.exports: $Exports<'deep-diff/examples/issue-62'>;
}
declare module 'deep-diff/examples/issue-70.js' {
  declare module.exports: $Exports<'deep-diff/examples/issue-70'>;
}
declare module 'deep-diff/examples/issue-71.js' {
  declare module.exports: $Exports<'deep-diff/examples/issue-71'>;
}
declare module 'deep-diff/examples/issue-72.js' {
  declare module.exports: $Exports<'deep-diff/examples/issue-72'>;
}
declare module 'deep-diff/examples/issue-74.js' {
  declare module.exports: $Exports<'deep-diff/examples/issue-74'>;
}
declare module 'deep-diff/examples/issue-78.js' {
  declare module.exports: $Exports<'deep-diff/examples/issue-78'>;
}
declare module 'deep-diff/examples/issue-83.js' {
  declare module.exports: $Exports<'deep-diff/examples/issue-83'>;
}
declare module 'deep-diff/examples/issue-88.js' {
  declare module.exports: $Exports<'deep-diff/examples/issue-88'>;
}
declare module 'deep-diff/examples/performance.js' {
  declare module.exports: $Exports<'deep-diff/examples/performance'>;
}
declare module 'deep-diff/index' {
  declare module.exports: $Exports<'deep-diff'>;
}
declare module 'deep-diff/index.js' {
  declare module.exports: $Exports<'deep-diff'>;
}
declare module 'deep-diff/test/tests.js' {
  declare module.exports: $Exports<'deep-diff/test/tests'>;
}
